package hva.nl.backendelection.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * The User class is used to store user information.
 *
 */

@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "users")
public class User {

    /**
     * The primary key for the 'users' table.
     *
     * This field is automatically generated by the database using the identity strategy.
     */
    @Id
    @Column(name = "user_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long userId;

    /**
     * The username of the user.
     *
     * This field represents the user's username in the 'users' table.
     */
    @Column
    private String username;

    /**
     * The password of the user.
     *
     * This field stores the user's hashed password.
     */
    @Column
    private String password;

    /**
     * The email of the user.
     *
     * This field represents the user's email address in the 'users' table.
     */
    @Column
    private String email;

    /**
     * The role of the user.
     *
     * This field stores the user's role (e.g., 'ADMIN', 'USER', etc.) for authorization purposes.
     */
    @Column
    private String role;
}
