package hva.nl.backendelection.model;

import jakarta.persistence.*; // Using jakarta.persistence for annotations
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The Vote class represents a vote cast by a user for a specific party.
 *
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@Table
public class Vote {

    /**
     * The primary key for the 'votes' table.
     *
     * This field is automatically generated by the database using the identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column
    private Long voteId;

    /**
     * The user ID who cast the vote.
     *
     * This field represents the ID of the user in the 'users' table.
     */
    @Column
    private Long userId;

    /**
     * The party ID for which the vote was cast.
     *
     * This field represents the ID of the party in the 'parties' table.
     */
    @Column
    private Long partyId;
}
